services:

# PostgreSQL Service
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresqlpw
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Elasticsearch Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_USERNAME=elasticsearch
      - ELASTIC_PASSWORD=elasticsearchpw
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

# RabbitMQ Service
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmqpw
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data

# Volumes for persistent data
volumes:
  postgres_data:
  elasticsearch_data:
  rabbitmq_data: