services:
  postgres_db:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      - "AutoAuctionNexus | PostgreSQL database server for Auction Service"

  mongo_db:
    container_name: mongodb_container
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/var/lib/mongodb/data
    labels:
      - "AutoAuctionNexus | MongoDB database server for Search Service"

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
    labels:
      - "AutoAuctionNexus | RabbitMQ"

volumes:
  postgres_data:
  mongodb_data:
  rabbitmq_data: